l=[10,20,30]
a={1:'a',2:'b',3:'c'}
value=['a']
d=dict.fromkeys(l,value)
value+=['b']
s=sorted(l,reverse=True)
b=sorted(a.keys(),reverse=True)
print(s)
print(b)
g={100:'a',200:'b',3:'c'}
s=g.copy()
print(s)
print(s.pop(200))
print(s.popitem())
print(s)
j={1:'a',2:'b',3:'c',4:'d'}
j.setdefault(4,"NA")
print(j)
